In [12]:
import warnings
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', 16)

In [14]:
data: pd.DataFrame = pd.read_csv(data_nm)

data.insert(2, 'year_month', pd.to_datetime(
    data.date, format='%Y-%m-%d').dt.strftime('%Y-%m')
)
data.year = data.year.astype('category')

print(f'data.shape = {data.shape}')
data.head(2)

data.shape = (3362796, 15)

,store_id,date,year_month,year,month,day,time,hour,minute,card_id,amount,installments,days_of_week,holiyday,weekend
0,Z0000,2016-12-14,2016-12,2016,12,14,18:05:31,18,5,D297BBA73F,5,1,WED,0,0
1,Z0000,2016-12-14,2016-12,2016,12,14,18:05:54,18,5,D297BBA73F,-5,1,WED,0,0

In [4]:
data.describe(include='object').T

                count  unique         top    freq
store_id      3362796    1775       Z0000   68773
date          3362796      24     2018-05  200462
time          3362796   85924    12:41:45     157
card_id       3362796  922522  53817035D4     835
days_of_week  3362796       7         SAT  533093

In [5]:
data.describe(exclude='object').T

,count,mean,std,min,25%,50%,75%,max
year,3362796.0,2017.247984,0.676447,2016.0,2017.0,2017.0,2018.0,2018.0
month,3362796.0,6.327452,3.333864,1.0,4.0,6.0,9.0,12.0
day,3362796.0,15.825904,8.786954,1.0,8.0,16.0,23.0,31.0
hour,3362796.0,15.351032,5.191531,0.0,12.0,16.0,19.0,23.0
minute,3362796.0,29.513739,17.319572,0.0,15.0,30.0,45.0,59.0
amount,3362796.0,145.962304,601.730590,-250000.0,32.0,75.0,150.0,250000.0
installments,3362796.0,1.012331,0.242138,1.0,1.0,1.0,1.0,36.0
holiyday,3362796.0,0.044313,0.205789,0.0,0.0,0.0,0.0,1.0
weekend,3362796.0,0.295959,0.456473,0.0,0.0,0.0,1.0,1.0

In [15]:
data_tmp = data.groupby(
    ['year_month', 'year']
).amount.size().reset_index()

figure = px.bar(
    data_tmp,
    x='year_month', y='amount', color='year',
    text_auto=True,
    width=800, height=400,
)
figure.update_layout(
    bargap=0.2, 
    margin=dict(t=20, l=20, b=20, r=20),
)
figure.show()